version: '3'
services:
  mongo:
    container_name: mongo_db
    image: mongo
    ports:
      - 27017:27019
    networks:
      - maqolaNetwork

  maqola:
      build: .
      ports:
        - "3000:3000"
      networks:
        - maqolaNetwork
networks:
  maqolaNetwork:
