# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -v ./cmd/main.go
      
  build-Front:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - working-directory: ./front
    - uses: actions/checkout@v3
    
    - name: node js build
      uses: actions/setup-node@v3
      with:
        node-version: 16
        
    - name: Install dependencies
      run: npm install --force
      
    - name: Build Front
      run: npm run build
    #- name: Test
     # run: go test -v ./...
 
  deployment:
    needs: build-Front
    runs-on: ubuntu-latest
    steps:
    - name: copy file via ssh
      uses: appleboy/scp-action@master
      with:
        host: 37.140.195.180
        username: root
        password: Ev9mo9uKd$$-
        port: 22
        source: ./main
        target: "/var/www/maqola.tj"
        
    - name: copy file via ssh
      uses: appleboy/scp-action@master
      with:
        host: 37.140.195.180
        username: root
        password: Ev9mo9uKd$$-
        port: 22
        source: ./ui
        target: "/var/www/maqola.tj"
        
    - name: copy file via ssh
      uses: appleboy/scp-action@master
      with:
        host: 37.140.195.180
        username: root
        password: Ev9mo9uKd$$-
        port: 22
        source: ./configs
        target: "/var/www/maqola.tj"
